name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: list
      run: ls
    - name: cd to root
      run: cd ..
    - name: make
      run: make
